#!/usr/bin/env bash

sudo -v

source src/setup/graphic_card.sh
source src/setup/packages.sh
source src/setup/peripheries.sh
source src/setup/shell.sh
source src/setup/software.sh
source src/setup/system_setup.sh

function display_progress() {
    local total_tasks=$1
    local completed_tasks=$2
    local start_time=$3

    # echo -e "Progress: $completed_tasks/$total_tasks tasks completed."
    # echo -e "$[{green}$completed_bar${red}$uncompleted_bar${reset}] $progress% completed."
    # echo -e "Elapsed Time: $minutes minutes $seconds seconds."

    local progress=$(echo "scale=2; $completed_tasks/$total_tasks*100" | bc)
    local completed_bar=$(echo "$progress/2" | bc)
    local uncompleted_bar=$(echo "50-$completed_bar" | bc)
    local minutes=$(echo "$elapsed_time/60" | bc)
    local seconds=$(echo "$elapsed_time%60" | bc)

    local green=$(tput setaf 2)
    local red=$(tput setaf 1)
    local reset=$(tput sgr0)

    local elapsed_time=$(echo "$(date +%s.%N) - $start_time" | bc)
    local progress_bar=$(echo -e "$green%${completed_bar}s$reset%${uncompleted_bar}s" | tr ' ' '=')
    local progress_bar=$(echo -e "$progress_bar $green$progress%$reset")
    local elapsed_time=$(echo -e "$green$minutes minutes $seconds seconds$reset")

    echo -ne "\rProgress: $completed_tasks/$total_tasks tasks completed.\n[$progress_bar]\nElapsed Time: $elapsed_time"
}

function desktop_environment_management() {
    local de=""
    if [ "$XDG_CURRENT_DESKTOP" ]; then
        de=$XDG_CURRENT_DESKTOP
    elif [ "$GDMSESSION" ]; then
        de=$GDMSESSION
    elif [ "$DESKTOP_SESSION" ]; then
        de=$DESKTOP_SESSION
    fi

    # execute la fonction de gestion du DE si elle existe
    if [ "$de" ]; then
        if [ -f src/setup/desktop_environments/$de.sh ]; then
            source src/setup/desktop_environments/$de.sh
        fi
    fi
}

function install_aur_helper() {
    if ! command -v yay &> /dev/null; then
        git clone https://aur.archlinux.org/yay-bin.git
        cd yay-bin
        makepkg -si --noconfirm
        cd ..
        rm -rf yay-bin
    fi
}

function main() {
    local start_time=$(date +%s.%N) 
    local total_tasks=6
    local completed_tasks=0

    if grep -q "^#\[multilib\]" "/etc/pacman.conf"; then
        sudo sed -i '/^#\[multilib\]/,/^#Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' "/etc/pacman.conf"
    fi
    sudo pacman -Syy --noconfirm
    sudo pacman -S --noconfirm git
    install_aur_helper
    yay -S --needed --noconfirm bc lolcat

    display_progress $total_tasks $completed_tasks $start_time
    system_setup            # 1
    ((completed_tasks++))
    display_progress $total_tasks $completed_tasks $start_time
    nvidia_drivers
    # install_video_drivers   # 2
    ((completed_tasks++))
    display_progress $total_tasks $completed_tasks $start_time
    chose_shell             # 3
    ((completed_tasks++))
    display_progress $total_tasks $completed_tasks $start_time
    install_peripheries     # 4
    ((completed_tasks++))
    display_progress $total_tasks $completed_tasks $start_time
    install_useful_packages # 5
    ((completed_tasks++))
    display_progress $total_tasks $completed_tasks $start_time
    install_useful_software # 6
    ((completed_tasks++))
    display_progress $total_tasks $completed_tasks $start_time

    sudo pacman -Rs --noconfirm bc lolcat
}

main

